# Generated by Django 3.2.20 on 2023-09-04 21:37

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Clientes',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.TextField(verbose_name='Nombre')),
                ('cedula', models.TextField(null=True, unique=True, verbose_name='Cedula')),
                ('telefono', models.TextField(verbose_name='Telefono')),
                ('correo', models.TextField(verbose_name='correo')),
                ('direccion', models.TextField(verbose_name='Direccion')),
                ('tipo', models.TextField(verbose_name='Tipo')),
            ],
            options={
                'verbose_name': 'Cliente',
                'verbose_name_plural': 'Clientes',
            },
        ),
        migrations.CreateModel(
            name='Doctores',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.TextField(verbose_name='Nombre')),
                ('telefono', models.TextField(verbose_name='Telefono')),
                ('cedula', models.TextField(null=True, unique=True, verbose_name='cedula')),
                ('direccion', models.TextField(verbose_name='direccion')),
                ('ciudad', models.TextField(verbose_name='Ciudad')),
            ],
            options={
                'verbose_name': 'Doctor',
                'verbose_name_plural': 'Doctores',
            },
        ),
        migrations.CreateModel(
            name='Inventario',
            fields=[
                ('cod_inven', models.IntegerField(primary_key=True, serialize=False, verbose_name='Codigo Inventario')),
                ('descripcion', models.TextField(verbose_name='Descripcion')),
                ('valor_costo', models.DecimalField(decimal_places=4, max_digits=20, verbose_name='Valor Costo')),
                ('valor_venta', models.DecimalField(decimal_places=4, max_digits=20, verbose_name='Valor Venta')),
                ('unidad_compra', models.TextField(max_length=3, verbose_name='Unidad Compra')),
                ('stock', models.DecimalField(decimal_places=4, max_digits=15, verbose_name='Stock')),
                ('stock_min', models.DecimalField(decimal_places=4, max_digits=15, verbose_name='Stock FIn')),
                ('factor', models.DecimalField(decimal_places=3, max_digits=15, verbose_name='Factor')),
                ('densidad', models.DecimalField(decimal_places=4, max_digits=15, verbose_name='Densidad')),
                ('tipo', models.TextField(verbose_name='Tipo')),
                ('cant', models.IntegerField(verbose_name='Cantidad')),
            ],
            options={
                'verbose_name': 'Inventario',
                'verbose_name_plural': 'Inventarios',
            },
        ),
        migrations.CreateModel(
            name='Usuario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cod_user', models.TextField(unique=True, verbose_name='Codigo')),
                ('nombre', models.TextField(verbose_name='Nombre')),
                ('apellido', models.TextField(verbose_name='Apellido')),
                ('correo', models.TextField(verbose_name='Correo')),
                ('tipo', models.TextField(verbose_name='Tipo')),
                ('ciudad', models.TextField(verbose_name='Ciudad')),
                ('pais', models.TextField(verbose_name='Pais')),
            ],
            options={
                'verbose_name': 'Usuario',
                'verbose_name_plural': 'Usuarios',
            },
        ),
        migrations.CreateModel(
            name='Visitas',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.TextField(verbose_name='Nombre')),
                ('cedula', models.TextField(null=True, unique=True, verbose_name='Cedula')),
                ('telefono', models.TextField(verbose_name='Telefono')),
                ('correo', models.TextField(verbose_name='Correo')),
                ('direccion', models.TextField(verbose_name='Direccion')),
                ('tipo', models.IntegerField(verbose_name='Tipo')),
                ('cod_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cotizador.usuario', verbose_name='Codigo Usuario')),
            ],
            options={
                'verbose_name': 'Visita',
                'verbose_name_plural': 'Visitas',
            },
        ),
        migrations.CreateModel(
            name='Formulas',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cod_formula', models.TextField(unique=True, verbose_name='Codigo Formula')),
                ('nombre', models.TextField(verbose_name='Nombre Formula')),
                ('precio_venta', models.DecimalField(decimal_places=2, default=0.0, max_digits=15)),
                ('precio_compra', models.DecimalField(decimal_places=2, default=0.0, max_digits=15)),
                ('dosis', models.IntegerField(default=0)),
                ('posologia', models.IntegerField(default=0)),
                ('cant', models.IntegerField(default=0)),
                ('cod_cliente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cotizador.clientes')),
                ('cod_doc', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cotizador.doctores')),
                ('cod_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cotizador.usuario')),
            ],
            options={
                'verbose_name': 'Formula',
                'verbose_name_plural': 'Formulas',
            },
        ),
        migrations.AddField(
            model_name='doctores',
            name='cod_user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cotizador.usuario', verbose_name='Codigo Ususario'),
        ),
        migrations.CreateModel(
            name='DetFormula',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cant', models.IntegerField(default=0)),
                ('date_joined', models.DateField(default=datetime.datetime.now)),
                ('obs', models.CharField(max_length=150, verbose_name='Observaciones')),
                ('activos', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cotizador.inventario')),
                ('formula', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cotizador.formulas')),
            ],
            options={
                'verbose_name': 'Detalle de Formula',
                'verbose_name_plural': 'Detalle de Formulas',
                'ordering': ['id'],
            },
        ),
        migrations.AddField(
            model_name='clientes',
            name='cod_user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cotizador.usuario', verbose_name='Codigo Ususario'),
        ),
    ]
